import os
import re
import argparse

def parse_hc_file(filepath):
    """
    Parses a single .hc file and extracts documentation.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.readlines()

    filename = os.path.basename(filepath)
    docs = {
        'filename': filename,
        'functions': [],
        'circuits': []
    }

    current_item = None
    
    # Regex patterns for V3 syntax
    func_pattern = re.compile(r'@function:\s+(\w+)\s*\((.*?)\)\s*(->\s*\w+)?')
    circ_pattern = re.compile(r'@circuit:\s+(\w+)')
    doc_pattern = re.compile(r'@doc:\s*"(.*)"')

    for line in content:
        line = line.strip()
        
        # Match Function
        func_match = func_pattern.match(line)
        if func_match:
            name, params, ret = func_match.groups()
            current_item = {
                'type': 'Function',
                'name': name,
                'signature': f"({params}) {ret if ret else ''}",
                'doc': 'No description provided.'
            }
            docs['functions'].append(current_item)
            continue

        # Match Circuit
        circ_match = circ_pattern.match(line)
        if circ_match:
            name = circ_match.group(1)
            current_item = {
                'type': 'Circuit',
                'name': name,
                'signature': 'Quantum Circuit',
                'doc': 'No description provided.'
            }
            docs['circuits'].append(current_item)
            continue

        # Match Docstring (applies to the last item found)
        doc_match = doc_pattern.match(line)
        if doc_match and current_item:
            current_item['doc'] = doc_match.group(1)

    return docs

def generate_markdown(all_docs):
    """
    Generates a Markdown string from the parsed docs.
    """
    md = "# 📚 HyperCode API Reference\n\n"
    md += "> Auto-generated by Research Agent Tooling\n\n"

    for file_doc in all_docs:
        if not file_doc['functions'] and not file_doc['circuits']:
            continue
            
        md += f"## 📄 {file_doc['filename']}\n\n"
        
        if file_doc['circuits']:
            md += "### ⚛️ Circuits\n"
            md += "| Name | Description |\n"
            md += "| :--- | :--- |\n"
            for item in file_doc['circuits']:
                md += f"| `{item['name']}` | {item['doc']} |\n"
            md += "\n"

        if file_doc['functions']:
            md += "### 🛠️ Functions\n"
            md += "| Name | Signature | Description |\n"
            md += "| :--- | :--- | :--- |\n"
            for item in file_doc['functions']:
                md += f"| `{item['name']}` | `{item['signature']}` | {item['doc']} |\n"
            md += "\n"
        
        md += "---\n\n"

    return md

def main():
    parser = argparse.ArgumentParser(description="HyperCode Auto-Docs Generator")
    parser.add_argument('input_dir', help="Directory to scan for .hc files")
    parser.add_argument('output_file', help="Output Markdown file")
    args = parser.parse_args()

    all_docs = []
    for root, _, files in os.walk(args.input_dir):
        for file in files:
            if file.endswith(".hc"):
                filepath = os.path.join(root, file)
                all_docs.append(parse_hc_file(filepath))

    markdown_output = generate_markdown(all_docs)
    
    with open(args.output_file, 'w', encoding='utf-8') as f:
        f.write(markdown_output)
    
    print(f"✅ Documentation generated at {args.output_file}")

if __name__ == "__main__":
    main()
